---
title: "US Wind Turbine Data Exploration in R"
author: "Gaurav Sharma"
date: "31/08/2020"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      dpi = 180,
                      fig.width = 8,
                      fig.height = 5)
library(tidyverse)
library(scales)
theme_set(theme_light())
```

### Lets load the data and see what do we have here
```{r}
ttfile <- tidytuesdayR::tt_load("2018-11-06")
us_wind <- ttfile$us_wind

us_wind_processed <- us_wind %>% 
    filter(!t_state %in% c("AK", "HI", "GU", "PR")) %>% 
    mutate(p_year = ifelse(p_year < -8000, NA, p_year))
```

### Lets check out some categorical features in the data
```{r}
us_wind %>% 
    count(t_state, sort = T)
```

```{r}
us_wind %>% 
    count(p_name, sort = T)
```

```{r}

us_wind %>% 
    count(t_manu, sort =T)
```

```{r}
world <- map_data("world") %>%
    filter(region == "USA",
           long < 100,
           lat > 25)

# If you want to plot a specific country
p1 <- ggplot() +
    geom_map(
        data = world,
        map = world,
        aes(x = long, y = lat, map_id = region),
        color = "white",
        fill = "gray50",
        alpha = 0.5
    )

p1 +
    geom_point(data = filter(us_wind, xlong < 100),
               aes(x = xlong, y = ylat))
```

```{r}
wind_projects <- us_wind_processed %>% 
    group_by(p_name, t_state) %>% 
    summarise(year = min(p_year),
              turbines = n(),
              lon = mean(xlong),
              lat = mean(ylat),
              lon_sd = sd(xlong),
              lat_sd = sd(ylat))

wind_projects %>%
    ggplot(aes(year)) +
    geom_histogram()
```

```{r}
p1 +
    geom_point(data = filter(wind_projects, lon < 100),
               aes(x = lon, y = lat, size = turbines, color = year))

```

```{r}

```

